name:Generate Code Coverage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install pnpm 
        run: npm install -g pnpm 

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run test
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}